### PR TITLE
update Readme.md. Add command to filter out incorrect lines in BBcall…

### LINKED ISSUE #97: Assertion failed for distance calculator
Hello alfgo authors,

I am evaluating aflgo with fuzzing benchmark [Magma](https://github.com/HexHive/magma).
When I tried to use `scripts/gen_distance_fast.py` in building Magma's targets, a lot of computations failed with the assertion
```
distance_calculator: main.cpp:174: std::vector<vertex_desc> cfg_calculation(graph_t &, std::ifstream &, std::ifstream &, std::ifstream &, unordered_map<std::string, double> &, unordered_map<std::string, double> &): Assertion `splits.size() == 2' failed.
```
On the other hand `scripts/genDistance.sh` worked in general, just being very very slow.

May I ask what is this assertion for and what maybe the cause of it? Is it fine to ignore it?

Please let me know if you would like to see the building scripts, binary, etc for this issue.
This happened for both the old aflgo and the current llvm11 version.

Thank you in advance!

### PR DESCRIPTION
**Pull request by waugustus**
Hi, I have updated `Readme.md` to help fix #97 .

Specifically, I added commands in the cleanup process to filter the empty lines in `BBnames.txt` and lines containing less or more than one comma in `BBcalls.txt`.

```
# Remove empty lines
grep -v "^$"
# Only keep lines with one comma mark
grep -Ev "^[^,]*$|^([^,]*,){2,}[^,]*$"
```

### CODE REVIEW

**Comment by mboehme** [comment]
Thanks for the PR,  @waugustus! Do we know where the empty lines or multi-comma entries are introduced?

**Comment by waugustus** [comment]
Unfortunately, I didn't find the reason for this bug. The code in `afl-llvm-pass.so.cc` seems to be ok, and this bug may be related to some characteristics of the target program (e.g., `libtiff`).

**Comment by mboehme** [comment]
The first grep deletes empty lines from BBnames.txt. The second grep removes lines without commas or with only a double-comma from BBCalls.txt. Just to confirm, the entire line with double-comma is a problem - we can't just substitute the double-comma with a single comma?

**Comment by waugustus** [comment]
Ideally, we should split these double-comma lines instead of just removing them. But it may be difficult to automate since we do not know the boundary of each entity. For example, the double-comma line in `libtiff` is

```
tif_dirwrite.c:3542,TIFFDataWidthtif_dir.c:60,setByteArray
```

which is a combination of `tif_dirwrite.c:3542,TIFFDataWidth` and `tif_dir.c:60,setByteArray`. It is hard to split this string `TIFFDataWidthtif_dir.c:60` correctly without prior knowledge.

If possible, I think the best solution is to find where these improper lines were introduced and avoid them. As an alternative, we can also just remove these lines to ensure the script works.

**Comment by mboehme** [comment]
Sounds good. Can you update your issue with this example? We keep the issue open and use this PR as a workaround.

Looks like a concurrency issue.

**Comment by mboehme** [comment]
> Can you update your issue with this example? We keep the issue open and use this PR as a workaround.

I meant to say, can you open an issue discussing this example? We merge this PR as a workaround.

**Comment by waugustus** [comment]
OK. I opened an issue in https://github.com/aflgo/aflgo/issues/123

**Pull request merged**
